### ISSUE TITLE
AttributeError: 'open3d.open3d.geometry.TriangleMesh' object has no attribute 'sample_points_uniformly'

### ISSUE THREAD

**Issue by rokudoyly** [intel-isl/Open3D#3504]
Greetings,
when I use `sample_points_uniformly` in my code, it reports that `AttributeError: 'open3d.open3d.geometry.TriangleMesh' object has no attribute 'sample_points_uniformly'` 
I have no idea how to resolve it. Thank you in advance.

The open3d version: 
`open3d                             0.12.0
open3d-python                      0.7.0.0
`

**Comment by rokudoyly** [comment]
When I update the open3d to 0.11.1, it solved. But there is a new bug:
`AttributeError: module 'open3d' has no attribute 'compute_point_cloud_to_point_cloud_distance'`

**Comment by ZhengdiYu** [comment]
I have a quite similar problem:
AttributeError: 'open3d.open3d.geometry.PointCloud' object has no attribute 'compute_nearest_neighbor_distance'

**Comment by rokudoyly** [comment]
> I have a quite similar problem:
> AttributeError: 'open3d.open3d.geometry.PointCloud' object has no attribute 'compute_nearest_neighbor_distance'

Update the open3d version can solve this problem.
