### ISSUE TITLE
PointNet jupyter notebook AttributeError: module 'open3d' has no attribute 'read_point_cloud'

### ISSUE THREAD

**Issue by albertotono** [intel-isl/Open3D#2630]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**

I got `AttributeError: module 'open3d' has no attribute 'read_point_cloud'` when I run the notebook provided in PointNet

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-8473ebe78773> in <module>
     13 
     14     # get next sample
---> 15     point_set, seg = test_dataset_seg.__getitem__(random_index)
     16 
     17     # create cloud for visualization

~/git_workspace/3d-deep-learning/Open3D-PointNet/datasets.py in __getitem__(self, index)
     73         cls = self.classes[self.datapath[index][0]]
     74         point_set = np.asarray(
---> 75             open3d.read_point_cloud(fn[1], format='xyz').points,
     76             dtype=np.float32)
     77         seg = np.loadtxt(fn[2]).astype(np.int64)

AttributeError: module 'open3d' has no attribute 'read_point_cloud'
```

**To Reproduce**
Notebook is here
https://github.com/intel-isl/Open3D-PointNet

**Expected behavior**
Clear visualization of the class.

**Comment by albertotono** [comment]
FYI, this happen also when I launch `open3d_visualilze.py` ( btw: not sure why it is spell in this way?! -.-) 

like `python open3d_visualilze.py`

```
(pytorch3d) alberto@tensorbook:~/git_workspace/3d-deep-learning/Open3D-PointNet$ python open3d_visualilze.py
Traceback (most recent call last):
  File "open3d_visualilze.py", line 41, in <module>
    v.visualize('02691156', '1a04e3eab45ca15dd86060f189eb133')
  File "open3d_visualilze.py", line 28, in visualize
    point_cloud = open3d.read_point_cloud(pts_path, format='xyz')
AttributeError: module 'open3d' has no attribute 'read_point_cloud'

```

**Comment by albertotono** [comment]
if I do `from open3d import read_point_cloud`

​I get

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-16-99be74fa924f> in <module>
----> 1 from open3d import read_point_cloud

ImportError: cannot import name 'read_point_cloud' from 'open3d' (/home/alberto/.local/lib/python3.8/site-packages/open3d/__init__.py)
```

**Comment by albertotono** [comment]
In the same environment when I try to run the Visualization demo it works perfectly. 
Not sure why the PointNet is not working it was done with 0.04 Open3D version, should I roll back?

**Comment by albertotono** [comment]
Is it possible to see the source-code?
![Screenshot from 2020-11-17 10-41-20](https://user-images.githubusercontent.com/11828200/99432798-82038500-28c1-11eb-9b2f-5ec6143efd62.png)

when I click on the link icon, it doesn't bring me to the source code

**Comment by albertotono** [comment]
I change to import open3d as o3d and it seems it is passing that point but I got this now

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-79a93c9425a5> in <module>
     16 
     17     # create cloud for visualization
---> 18     cloud = o3d.PointCloud()
     19     cloud.points = o3d.Vector3dVector(point_set)
     20     cloud.colors = o3d.Vector3dVector(read_pointnet_colors(seg.numpy()))

AttributeError: module 'open3d' has no attribute 'PointCloud'

```


```
# get next sample
    point_set, seg = test_dataset_seg.__getitem__(random_index)

    # create cloud for visualization
    cloud = o3d.PointCloud()
    cloud.points = o3d.Vector3dVector(point_set)
    cloud.colors = o3d.Vector3dVector(read_pointnet_colors(seg.numpy()))

    # perform inference in GPU
    points = Variable(point_set.unsqueeze(0))
    points = points.transpose(2, 1)
    if torch.cuda.is_available():
        points = points.cuda()
    pred_logsoft, _ = classifier(points)

    # move data back to cpu for visualization
    pred_logsoft_cpu = pred_logsoft.data.cpu().numpy().squeeze()
    pred_soft_cpu = np.exp(pred_logsoft_cpu)
    pred_class = np.argmax(pred_soft_cpu)

    # let's visualize the input sample
    visualizer.add_geometry(cloud)
    visualizer.show()
    
    # Visualize probabilities
    plt.xticks(list(classes_dict.values()), list(classes_dict.keys()),rotation=90)
    plt.xlabel('Classes')
    plt.ylabel('Probabilities')
    plt.plot(list(classes_dict.values()), pred_soft_cpu)
    plt.show()

    input('Your object is a [{}] with probability {:0.3}. Press enter to continue!'
          .format(list(classes_dict.keys())[pred_class], pred_soft_cpu[pred_class]))
```

**Comment by albertotono** [comment]
ok I replace with this new

- 
```
- open3d.geometry.PointCloud()
- open3d.utility.Vector3dVector(np_points)

```

**Comment by TSG1498** [comment]
Hello!
I am running the same code as presented above and got the same error. Can you elaborate on how u fixed this issue?

**Comment by hannsta** [comment]
@TSG1498 It appears that this is related to the version of open3d you are using. You can either try an older version or, you may be able to do what I did, by manually  changing all references of:

`open3d.read_point_cloud`
to
`open3d.io.read_point_cloud`

**Comment by samhithaaaa** [comment]
> ok I replace with this new
> 
> 
> ```
> - open3d.geometry.PointCloud()
> - open3d.utility.Vector3dVector(np_points)
> ```

Hi, it throws AttributeError: module 'open3d' has no attribute 'geometry' when replaced.Any fixes here?

**Comment by srcoulombe** [comment]
@samhithaaaa `open3d.geometry.PointCloud()` works with version 0.14.1.

Maybe check your version?

**Comment by jiapei-nexera** [comment]
Yeah.... Clearly, a version issue... 
**Open3D** is a headache package.... When will it be possible to get a stable and compatible open source, rather than just a viewer tool???

**Comment by kimsooyoung** [comment]
Quite been a while from last comment but I'd like to share how I resolved this!

## API update _(Due to horrible Open3D )_
* open3d.read_point_cloud => open3d.io.read_point_cloud
* o3.PointCloud() => open3d.geometry.PointCloud()
* o3.Vector3dVector =>  open3d.utility.Vector3dVector 

## Visualiization

```
cloud = o3.geometry.PointCloud()
...
o3.visualization.draw_geometries([cloud])
```
and result was

![image](https://user-images.githubusercontent.com/12381733/235179609-b73a742f-d77c-42ae-819b-ca95b43ec904.png)

TADA~
