### ISSUE TITLE
Archlinux build fails 

### ISSUE THREAD

**Issue by WysokiStudent** [intel-isl/Open3D#3520]
**Describe the bug**
CMake's configure stage fails with:
```
-- Using prebuilt third-party library Filament
-- GLIBC version 2.33 found: Downloading Open3D Filament binary.
-- Filament is located at /home/zannzetsu/Open3D/build/filament/src/ext_filament
CMake Error at 3rdparty/find_dependencies.cmake:971 (find_library):
  Could not find CPPABI_LIBRARY using the following names: c++abi
Call Stack (most recent call first):
  CMakeLists.txt:613 (include)
```
This applies to both 0.12 and master.

**To Reproduce**
```
git clone --recurse-submodules --depth=1 git@github.com:intel-isl/Open3D.git
cd Open3D
mkdir build
cd build
cmake ..
```
**Expected behavior**
Configure succeeds along with the following make.

**Environment (please complete the following information):**

- Operating system: Arch Linux
- Python version: Python 3.9.5
- Open3D version: Currently installed is 0.9 but I wanted to install 0.12 or master
- Is this remote workstation?: no
- How did you install Open3D?: 0.9 from AUR, 0.12 from source
- Compiler version (if built from source): gcc (GCC) 11.1.0

**Additional information**
find_dependencies fails here
```
        if (NOT CLANG_LIBDIR)
            find_library(CPPABI_LIBRARY c++abi PATH_SUFFIXES
                         llvm-11/lib llvm-10/lib llvm-9/lib llvm-8/lib llvm-7/lib
                         REQUIRED)
```
Here is the output of `llvm-as --version`
```
LLVM (http://llvm.org/):
  LLVM version 11.1.0
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: skylake
  ```
 I can install `pacman -S libc++abi` but the version is `libc++abi 12.0.0-1`

**Comment by stotko** [comment]
Thanks for trying out Open3D on Arch Linux. I have added support for Clang 12 in #3522. Could you give it a try and check whether this fixes your issue on Arch Linux?

**Comment by WysokiStudent** [comment]
I just tried and the error message is:
```
-- Using prebuilt third-party library Filament
-- GLIBC version 2.33 found: Downloading Open3D Filament binary.
-- Filament is located at /home/zannzetsu/Open3D/build/filament/src/ext_filament
CMake Error at 3rdparty/find_dependencies.cmake:977 (find_library):
  Could not find CPP_LIBRARY using the following names: c++
Call Stack (most recent call first):
  CMakeLists.txt:613 (include)
```
I'm not quite sure where to go from here, no obvious sources of this error come to my mind.

**Comment by stotko** [comment]
Thanks. `c++` seems to be a Ubuntu-specific thing and Open3D only officially supports Ubuntu so far. I can try to fix this as well, but I would need your help since I work on Ubuntu 20.04 and cannot reproduce this there. As a first step, could you attach the full log (that includes the current error message) when running CMake?

**Comment by WysokiStudent** [comment]
You are right, installing `libc++` did allow cmake to configure the project. Now I am facing compile issues.
```
[ 29%] Building CXX object cpp/open3d/core/CMakeFiles/core.dir/nns/NanoFlannIndex.cpp.o                                                                                          │
In file included from /home/zannzetsu/Open3D/3rdparty/parallelstl/include/pstl/execution:20,                                                                                     │
                 from /home/zannzetsu/Open3D/cpp/open3d/utility/ParallelScan.h:32,                                                                                               │
                 from /home/zannzetsu/Open3D/cpp/open3d/core/nns/NanoFlannIndex.cpp:36:                                                                                          │
/home/zannzetsu/Open3D/3rdparty/parallelstl/include/pstl/internal/execution_defs.h:29:7: error: redefinition of ‘class __pstl::execution::v1::sequenced_policy’                  │
   29 | class sequenced_policy                                                                                                                                                   │
      |       ^~~~~~~~~~~~~~~~                                                                                                                                                   │
In file included from /usr/include/c++/11.1.0/pstl/glue_memory_defs.h:13,                                                                                                        │
                 from /usr/include/c++/11.1.0/memory:144,                                                                                                                        │
                 from /home/zannzetsu/Open3D/cpp/open3d/core/Tensor.h:31,                                                                                                        │
                 from /home/zannzetsu/Open3D/cpp/open3d/core/nns/NanoFlannIndex.h:31,                                                                                            │
                 from /home/zannzetsu/Open3D/cpp/open3d/core/nns/NanoFlannIndex.cpp:27:                                                                                          │
/usr/include/c++/11.1.0/pstl/execution_defs.h:23:7: note: previous definition of ‘class __pstl::execution::v1::sequenced_policy’                                                 │
   23 | class sequenced_policy                                                                                                                                                   │
      |       ^~~~~~~~~~~~~~~~                                                                                                                                                   │
In file included from /home/zannzetsu/Open3D/3rdparty/parallelstl/include/pstl/execution:20,                                                                                     │
                 from /home/zannzetsu/Open3D/cpp/open3d/utility/ParallelScan.h:32,                                                                                               │
                 from /home/zannzetsu/Open3D/cpp/open3d/core/nns/NanoFlannIndex.cpp:36:                                                                                          │
/home/zannzetsu/Open3D/3rdparty/parallelstl/include/pstl/internal/execution_defs.h:52:7: error: redefinition of ‘class __pstl::execution::v1::parallel_policy’                   │
   52 | class parallel_policy                                                                                                                                                    │
      |       ^~~~~~~~~~~~~~~ 
```
and multiple similar errors after that. Should I open a seperate issue?

**Comment by stotko** [comment]
Thanks. This looks like a conflict with C++17 which became the default standard for GCC 11. You can try an older version of GCC or use Clang instead in the meantime. I will take a look into this as well.

**Comment by WysokiStudent** [comment]
I tried building with clang but got a different error instead:
```
[ 74%] Built target Open3D
[ 74%] Building CXX object cpp/tools/CMakeFiles/ViewGeometry.dir/ViewGeometry.cpp.o
make[2]: *** Brak reguł do zrobienia obiektu 'libjpeg-turbo-install/lib/libturbojpeg.a', wymaganego przez 'bin/ViewGeometry'. Stop.
make[1]: *** [CMakeFiles/Makefile2:2171: cpp/tools/CMakeFiles/ViewGeometry.dir/all] Błąd 2
make: *** [Makefile:136: all] Błąd 2
```

This translates roughly to "No rule to create object 'libjpeg-turbo-install/lib/libturbojpeg.a' required by 'bin/ViewGeometry'.

I do have libturbojpeg installed.
`sudo pacman -Q | grep libjpeg`:
```
lib32-libjpeg-turbo 2.1.0-1
libjpeg-turbo 2.1.0-1
```
I appreciate the work you put into solving this problem and understand that if this is an arch centric issue I will have to solve it myself.

**Comment by stotko** [comment]
Open3D tries to find `libturbojpeg` only if `USE_SYSTEM_JPEG` and `BUILD_AZURE_KINECT` are both set to `ON`. Could you run `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..` and attach the `compile_commands.json` file which should be located in the `build` directory? If possible, could you also uninstall `libjpegturbo` and try again?

**Comment by WysokiStudent** [comment]
Unfortunately `libjpegturbo` is a hard dependency in my setup. I will try to experiment with using system libraries if you don't mind.  I will set the appropriate USE_SYSTEM variables to ON and report back when I have the `compile_commands.json`

**Comment by WysokiStudent** [comment]
Apparently GitHub doesn't support .json files.
[compile_commands.txt](https://github.com/intel-isl/Open3D/files/6571250/compile_commands.txt)

I enabled usage of the following system libs:
```
# 3rd-party build options
option(USE_BLAS                   "Use BLAS/LAPACK instead of MKL"           OFF)
option(USE_SYSTEM_EIGEN3          "Use system pre-installed eigen3"          ON)
option(USE_SYSTEM_FLANN           "Use system pre-installed flann"           ON)
option(USE_SYSTEM_FMT             "Use system pre-installed fmt"             ON)
option(USE_SYSTEM_GLEW            "Use system pre-installed glew"            ON)
option(USE_SYSTEM_GLFW            "Use system pre-installed glfw"            ON)
option(USE_SYSTEM_GOOGLETEST      "Use system pre-installed googletest"      ON)
option(USE_SYSTEM_IMGUI           "Use system pre-installed imgui"           OFF)
option(USE_SYSTEM_JPEG            "Use system pre-installed jpeg"            ON)
option(USE_SYSTEM_LIBLZF          "Use system pre-installed liblzf"          ON)
option(USE_SYSTEM_PNG             "Use system pre-installed png"             ON)
option(USE_SYSTEM_PYBIND11        "Use system pre-installed pybind11"        ON)
option(USE_SYSTEM_QHULL           "Use system pre-installed qhull"           ON)
option(USE_SYSTEM_TINYGLTF        "Use system pre-installed tinygltf"        OFF)
option(USE_SYSTEM_TINYOBJLOADER   "Use system pre-installed tinyobjloader"   ON)
```
I'm building Open3D as we speak. If it fails I will post an error message.

**Comment by WysokiStudent** [comment]
New error message:
```
[ 27%] Built target core
Consolidate compiler generated dependencies of target geometry
[ 27%] Building CXX object cpp/open3d/geometry/CMakeFiles/geometry.dir/Line3D.cpp.o
/home/zannzetsu/Open3D/cpp/open3d/geometry/Line3D.cpp:30:11: error: no member named 'transform' in 'open3d::geometry::Line3D'
    this->transform(t);
    ~~~~  ^
/home/zannzetsu/Open3D/cpp/open3d/geometry/Line3D.cpp:324:11: error: no member named 'transform' in 'open3d::geometry::Segment3D'
    this->transform(t);
    ~~~~  ^
2 errors generated.
make[2]: *** [cpp/open3d/geometry/CMakeFiles/geometry.dir/build.make:202: cpp/open3d/geometry/CMakeFiles/geometry.dir/Line3D.cpp.o] Błąd 1
make[1]: *** [CMakeFiles/Makefile2:1298: cpp/open3d/geometry/CMakeFiles/geometry.dir/all] Błąd 2
make: *** [Makefile:136: all] Błąd 2

```

**Comment by stotko** [comment]
Thanks. I'm able to reproduce the first build error (`sequenced_policy`) with GCC 10 and C++17 on Ubuntu 20.04. Regarding the latest error: What version of `Eigen` do have installed on Arch Linux?

**Comment by WysokiStudent** [comment]
Good to know that my issue was not spurious. My version of Eigen is `eigen 3.3.9-1`.

**Comment by WysokiStudent** [comment]
Apparently my second issue is not new, it was mention before in #2487 and #2885

**Comment by stotko** [comment]
I have pushed a fix for the `sequenced_policy` build error. Could you pull the latest changes from #3522 and check if this fixes the issue for you as well when compiling with GCC, .i.e. `cmake ..` without any additional settings?

Since the issue with a system version of `Eigen` is different, we will address this separate from this issue.

**Comment by WysokiStudent** [comment]
I can confirm that the proposed change fixed the first make issue. Nice.
