### ISSUE TITLE
Azure kinect support

### ISSUE THREAD

**Issue by Fred3D-tech** [intel-isl/Open3D#2750]
Testing with Windows 10 and Ubuntu 18.04 and 20.04. Tested on 3 different computers with fresh install.
Tried pip package, conda package and build from source.
Open3d 0.11.2
testing your script azure_capture.py with 0.11.2 and it is just not working. It worked with open3d 0.9.
The code we developed and was working with 0.9 is just not working anymore. 
 Do you still support Azure Kinect ?
The error message on windows 10:
C:\Anaconda3\envs\pythonProject\python.exe C:/Anaconda3/sensors/azure_capture.py
Traceback (most recent call last):
  File "C:/Anaconda3/sensors/azure_capture.py", line 285, in <module>
    config = o3d.io.AzureKinectSensorConfig()
AttributeError: module 'open3d.cpu.pybind.io' has no attribute 'AzureKinectSensorConfig'

**Comment by yxlao** [comment]
Please compile from source and try again. It has been added back in https://github.com/intel-isl/Open3D/pull/2648 recently. It will be updated in the December wheel release.

**Comment by mrmotallebi** [comment]
@yxlao Are you sure this has been resolved? I can't import the class on v0.12 for Linux, getting the package using `pip`.
Also, when I look into the wheel `open3d-0.12.0-cp36-cp36m-manylinux2014_x86_64.whl` on https://pypi.org/project/open3d/#files, the file _build_config.py says:
>     "BUILD_AZURE_KINECT" : "OFF" == "ON",

**Comment by kaixin-bai** [comment]
same problem for python3.6 and open3d 0.12.0
